version: "3.8"

services:
  #################################################################
  # Traefik Reverse Proxy
  #################################################################
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    networks:
      - my_media
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/config/traefik/acme.json:/acme.json
    command:
      # Docker provider
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # Let's Encrypt / ACME (HTTP challenge)
      - "--certificatesresolvers.myresolver.acme.email=csherman@mailbox.org"
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"

    environment:
      - TZ=America/Los_Angeles

    # We define the "Authelia" ForwardAuth middleware on Traefik itself,
    # so each service can reference "authelia@docker".
    labels:
      - "traefik.enable=true"  # <-- Add this
      # We create a middleware named "authelia" that points to the Authelia service
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.twosix.su"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"

      # (optional) Another middleware to redirect HTTP->HTTPS for the auth domain
      - "traefik.http.middlewares.authelia-redirect.redirectscheme.scheme=https"

      #################################
      # Traefik router for Authelia itself will live on the Authelia container
      # but you *could* define it here if you prefer. We'll do it on authelia below.
      #################################

  #################################################################
  # Authelia (SSO Portal)
  #################################################################
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    networks:
      - my_media
    volumes:
      - /srv/config/authelia:/config
    # Authelia listens on port 9091 internally
    # We'll define the router/labels so "auth.twosix.su" can reach it

    labels:
      - "traefik.enable=true"

      # Secure router for https://auth.twosix.su
      - "traefik.http.routers.authelia.rule=Host(`auth.twosix.su`)"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls.certresolver=myresolver"

      # Insecure router for http -> https redirect
      - "traefik.http.routers.authelia-insecure.rule=Host(`auth.twosix.su`)"
      - "traefik.http.routers.authelia-insecure.entrypoints=web"
      - "traefik.http.routers.authelia-insecure.middlewares=authelia-redirect"

    environment:
      - TZ=America/Los_Angeles

  #################################################################
  # Jellyfin at twosix.su
  #################################################################
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /srv/config/jellyfin:/config
      - /srv/media:/media
    networks:
      - my_media
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      # HTTPS router
      - "traefik.http.routers.jellyfin.rule=Host(`twosix.su`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
      # Use Authelia forward auth
      #- "traefik.http.routers.jellyfin.middlewares=authelia@docker"

      # HTTP -> HTTPS
      - "traefik.http.routers.jellyfin-insecure.rule=Host(`twosix.su`)"
      - "traefik.http.routers.jellyfin-insecure.entrypoints=web"
      - "traefik.http.routers.jellyfin-insecure.middlewares=jellyfin-redirect"
      - "traefik.http.middlewares.jellyfin-redirect.redirectscheme.scheme=https"

      - "traefik.docker.network=my_media"

  #################################################################
  # Sonarr at sonarr.twosix.su
  #################################################################
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /srv/config/sonarr:/config
      - /srv/media/shows:/tv
      - /srv/downloads:/downloads
    networks:
      - my_media
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.sonarr.rule=Host(`sonarr.twosix.su`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=myresolver"
      # Authelia SSO
      - "traefik.http.routers.sonarr.middlewares=authelia@docker"

      - "traefik.http.routers.sonarr-insecure.rule=Host(`sonarr.twosix.su`)"
      - "traefik.http.routers.sonarr-insecure.entrypoints=web"
      - "traefik.http.routers.sonarr-insecure.middlewares=sonarr-redirect"
      - "traefik.http.middlewares.sonarr-redirect.redirectscheme.scheme=https"
      - "traefik.docker.network=my_media"

  #################################################################
  # Radarr at radarr.twosix.su
  #################################################################
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /srv/config/radarr:/config
      - /srv/media/movies:/movies
      - /srv/downloads:/downloads
    networks:
      - my_media
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.twosix.su`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls.certresolver=myresolver"
      - "traefik.http.routers.radarr.middlewares=authelia@docker"

      - "traefik.http.routers.radarr-insecure.rule=Host(`radarr.twosix.su`)"
      - "traefik.http.routers.radarr-insecure.entrypoints=web"
      - "traefik.http.routers.radarr-insecure.middlewares=radarr-redirect"
      - "traefik.http.middlewares.radarr-redirect.redirectscheme.scheme=https"
      - "traefik.docker.network=my_media"

  #################################################################
  # Lidarr
  #################################################################
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /srv/config/lidarr:/config
      - /srv/media/music:/music
      - /srv/downloads:/downloads
    networks:
      - my_media
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.twosix.su`)"
      - "traefik.http.routers.lidarr.entrypoints=websecure"
      - "traefik.http.routers.lidarr.tls.certresolver=myresolver"
      - "traefik.http.routers.lidarr.middlewares=authelia@docker"

      - "traefik.http.routers.lidarr-insecure.rule=Host(`lidarr.twosix.su`)"
      - "traefik.http.routers.lidarr-insecure.entrypoints=web"
      - "traefik.http.routers.lidarr-insecure.middlewares=lidarr-redirect"
      - "traefik.http.middlewares.lidarr-redirect.redirectscheme.scheme=https"
      - "traefik.docker.network=my_media"

  #################################################################
  # Bazarr
  #################################################################
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /srv/config/bazarr:/config
      - /srv/media/shows:/tv
      - /srv/media/movies:/movies
    networks:
      - my_media
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.twosix.su`)"
      - "traefik.http.routers.bazarr.entrypoints=websecure"
      - "traefik.http.routers.bazarr.tls.certresolver=myresolver"
      - "traefik.http.routers.bazarr.middlewares=authelia@docker"

      - "traefik.http.routers.bazarr-insecure.rule=Host(`bazarr.twosix.su`)"
      - "traefik.http.routers.bazarr-insecure.entrypoints=web"
      - "traefik.http.routers.bazarr-insecure.middlewares=bazarr-redirect"
      - "traefik.http.middlewares.bazarr-redirect.redirectscheme.scheme=https"
      - "traefik.docker.network=my_media"

  #################################################################
  # Prowlarr
  #################################################################
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /srv/config/prowlarr:/config
    networks:
      - my_media
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.twosix.su`)"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls.certresolver=myresolver"
      - "traefik.http.routers.prowlarr.middlewares=authelia@docker"

      - "traefik.http.routers.prowlarr-insecure.rule=Host(`prowlarr.twosix.su`)"
      - "traefik.http.routers.prowlarr-insecure.entrypoints=web"
      - "traefik.http.routers.prowlarr-insecure.middlewares=prowlarr-redirect"
      - "traefik.http.middlewares.prowlarr-redirect.redirectscheme.scheme=https"
      - "traefik.docker.network=my_media"
  #################################################################
  # JellySeer
  #################################################################
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /srv/config/jellyseerr:/app/config
    networks:
      - my_media
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr.rule=Host(`get.twosix.su`)"
      - "traefik.http.routers.jellyseerr.entrypoints=websecure"
      - "traefik.http.routers.jellyseerr.tls.certresolver=myresolver"

      - "traefik.http.routers.jellyseerr-insecure.rule=Host(`get.twosix.su`)"
      - "traefik.http.routers.jellyseerr-insecure.entrypoints=web"
      - "traefik.docker.network=my_media"

  #################################################################
  # SABnzbd
  #################################################################
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /srv/config/sabnzbd:/config
      - /srv/downloads:/downloads
    networks:
      - my_media
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.twosix.su`)"
      - "traefik.http.routers.sabnzbd.entrypoints=websecure"
      - "traefik.http.routers.sabnzbd.tls.certresolver=myresolver"
      - "traefik.http.routers.sabnzbd.middlewares=authelia@docker"

      - "traefik.http.routers.sabnzbd-insecure.rule=Host(`sabnzbd.twosix.su`)"
      - "traefik.http.routers.sabnzbd-insecure.entrypoints=web"
      - "traefik.http.routers.sabnzbd-insecure.middlewares=sabnzbd-redirect"
      - "traefik.http.middlewares.sabnzbd-redirect.redirectscheme.scheme=https"
      - "traefik.docker.network=my_media"

networks:
  my_media:
    driver: bridge
